### ISSUE TITLE
BUILDUI: Fix object placement

### ISSUE THREAD

**Issue by marvis999** [Sparker95/Vindicta#263]
- Objects change position drastically from where you place them.
- Some players see objects in a different position than where they were placed by another player

**Comment by Sparker95** [comment]
> Some players see objects in a different position than where they were placed by another player
I suspect that it might be due to arma server sending updates on 'static' objects very rare, therefore it doesn't synchronize position or rotation properly. Not sure.

**Comment by marvis999** [comment]
Placement does work fine if you launch the mission in the editor. I remember it working fine on the server as well, and I don't think billw made changes since those tests.

So yea, network/desynch problem of some sort?

**Comment by Sparker95** [comment]
> So yea, network/desynch problem of some sort?
Probably related to arma itself. You remember when you create a camp it creates a small composition of simple objects: backpacks, food packs, etc. They initially spawn heading north and not rotated properly. Then they eventually rotate to where they need to look at. It's because arma prioritizes updates of more dynamic objects over more static objects. Probably same issue is here.

I dunno, we can remoteExec code to force-set the pos and direction of objects globally maybe. Worth trying. Need to investigate more.

**Comment by marvis999** [comment]
I havent noticed it on camps, but the roadblock we made yesterday took ~20s before objects suddenly rotated.

**Comment by Sparker95** [comment]
Maybe setPos and setDir globally could help it then, yeah. Lets try that.

**Comment by marvis999** [comment]
Fixed.
