### ISSUE TITLE
Features Request 

### ISSUE THREAD

**Issue by teemo0803** [Sparker95/Vindicta#645]
1.  Headless Client

> Offload the AIs

2. ACEX FOOD SUPPORT

> More gaming experience

3.Bodied Clean
> BETTER FPS

**Comment by Sparker95** [comment]
Hi!

1. Not coming any time soon. A lot of code must be redone and we don't have enough people programming so that I can try to do it. Besides the scenario seems to work good enough on good hardware, I don't see much need for it, considering how much time it will take to do it.
2. Never heard of it.
3. What is it? Deletion of killed bodies? It happens already, although not all items are deleted sometimes.

Please in the future just create an issue per each feature, thanks.
