### ISSUE TITLE
Incite dialogue option doesn't work

### ISSUE THREAD

**Issue by Sparker95** [Sparker95/Vindicta#763]

**Comment by canuckbrian** [comment]
Any idea when this is going to be fixed? My friends and I have made a lot of progress capturing police stations, military locations, and outposts, but we cannot get towns to swing to our favor because of this. We've gotten our Influence up to 100% on some towns near military bases, only to watch it drop more than 10% now with no way to increase it again.

**Comment by Jasperdoit** [comment]
Have you actually captured the town? To do that you need to get friendly AI units you recruited at camps to occupy (reinforce) them.

**Comment by canuckbrian** [comment]
> Have you actually captured the town? To do that you need to get friendly AI units you recruited at camps to occupy (reinforce) them.

I was not aware of that. Thank you. I have now captured a town. Side says "West" now, instead of Unknown.

**Comment by Sparker95** [comment]
It's fixed when I have time to look into this, and now I have none.

**Comment by Sparker95** [comment]
Fixed in 98e92a2
