### ISSUE TITLE
Global Mobilization Factions Cargo Capacity

### ISSUE THREAD

**Issue by GrumpyTanker** [Sparker95/Vindicta#773]
Seems all vehicles from the Global Mobilization CDLC have a cargo capacity of 4, which prevents them from being able to load large arsenal crates. Makes it very annoying to loot an outpost.

**Comment by Sparker95** [comment]
Hi!

Yes I know this, but it's up to ACE team to handle this.

Maybe I can think of a workaround though. These values can be overriden by script, and since we always know the kind of vehicle we spawn, perhaps we can set these values manually. But I would prefer ACE team to fix that. Or maybe we need some compatibility files for GM CDLC? I haven't checked it for some time.

**Comment by Sparker95** [comment]
I guess that this PR will fix cargo space in GM vehicles, but I am not completely sure:
https://github.com/acemod/ACE3/pull/7835

**Comment by Sparker95** [comment]
Fixed in 5e0fcba
